const ACTION_TYPES = {
  //User Related
  SIGN_UP_USER: 'SIGN_UP_USER',
  REMOVE_SIGN_UP_USER: 'REMOVE_SIGN_UP_USER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOCATION: 'USER_LOCATION', 
};

export { ACTION_TYPES };
